/* generated by build.py — do not edit by hand */
window.SITE = {
  "logo": "assets/logo.png",
  "imgBase": "assets/img",
  "widths": [
    480,
    900,
    1500
  ],
  "groups": [
    {
      "label": "group 1",
      "works": [
        {
          "slug": "w01",
          "ar": 1.0,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w02",
          "ar": 1.3333,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w03",
          "ar": 1.7549,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w04",
          "ar": 1.0,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w05",
          "ar": 1.0,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w06",
          "ar": 1.3333,
          "sizes": [
            480,
            900,
            1500
          ]
        }
      ]
    },
    {
      "label": "group 2",
      "works": [
        {
          "slug": "w07",
          "ar": 1.0,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w08",
          "ar": 1.7549,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w09",
          "ar": 1.0,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w10",
          "ar": 1.3333,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w11",
          "ar": 1.0,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w12",
          "ar": 1.3333,
          "sizes": [
            480,
            900,
            1500
          ]
        }
      ]
    },
    {
      "label": "group 3",
      "works": [
        {
          "slug": "w13",
          "ar": 1.0,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w14",
          "ar": 1.0089,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w15",
          "ar": 1.0,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w16",
          "ar": 1.0,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w17",
          "ar": 1.0,
          "sizes": [
            480,
            900,
            1500
          ]
        },
        {
          "slug": "w18",
          "ar": 1.0,
          "sizes": [
            480,
            900,
            1500
          ]
        }
      ]
    }
  ]
};
