/* generated by build.py — do not edit by hand */
window.SITE = {
  "logo": "assets/logo.png",
  "imgBase": "assets/img",
  "widths": [
    480,
    900,
    1500
  ],
  "columns": [
    {
      "label": "petals",
      "works": [
        {
          "slug": "img-2159-1",
          "ar": 1.3333
        },
        {
          "slug": "abstrakt-cover-2-1",
          "ar": 1.3333
        }
      ]
    },
    {
      "label": "club room",
      "works": [
        {
          "slug": "494370bc-1962-46a6-b7f1-067a058d6f9b-1",
          "ar": 1.0
        },
        {
          "slug": "subrosa-4-1",
          "ar": 1.0
        },
        {
          "slug": "a4-28-3-1",
          "ar": 0.9993
        }
      ]
    },
    {
      "label": "prostor",
      "works": [
        {
          "slug": "frame-1907-1",
          "ar": 1.0
        },
        {
          "slug": "swinwarrior1998-2",
          "ar": 1.0
        },
        {
          "slug": "image-53",
          "ar": 1.0089
        }
      ]
    },
    {
      "label": "posters",
      "works": [
        {
          "slug": "double-poster-mockup-1",
          "ar": 1.7549
        },
        {
          "slug": "mockup-01-1",
          "ar": 1.0
        },
        {
          "slug": "sea-view-rock-1",
          "ar": 1.0
        }
      ]
    },
    {
      "label": "jinx bomb",
      "works": [
        {
          "slug": "frame-21-1",
          "ar": 1.0
        },
        {
          "slug": "image-51",
          "ar": 1.0
        },
        {
          "slug": "img-6242-1",
          "ar": 1.7549
        }
      ]
    },
    {
      "label": "3d",
      "works": [
        {
          "slug": "img-2659-1",
          "ar": 1.0
        },
        {
          "slug": "camphoto-351212254-1",
          "ar": 1.0
        }
      ]
    },
    {
      "label": "type",
      "works": [
        {
          "slug": "image-50",
          "ar": 1.3333
        },
        {
          "slug": "image-60",
          "ar": 1.0
        }
      ]
    },
    {
      "label": "more",
      "works": [
        {
          "slug": "just-a-regular-rock-1",
          "ar": 1.0
        },
        {
          "slug": "photo-2022-04-30-01-28-01-1",
          "ar": 1.0
        }
      ]
    }
  ]
};
