/* generated by build.py — do not edit by hand */
window.SITE = {
  "logo": "assets/logo.png",
  "imgBase": "assets/img",
  "videoBase": "assets/video",
  "widths": [
    480,
    900,
    1500
  ],
  "columns": [
    {
      "label": "petals",
      "works": [
        {
          "slug": "petals-coral-veo3",
          "ar": 1.3324,
          "video": true,
          "key": "petals-coral-veo3"
        },
        {
          "slug": "lux-1-2",
          "ar": 0.5626,
          "key": "lux_1"
        },
        {
          "slug": "img-2159-1",
          "ar": 1.3333,
          "key": "IMG_2159"
        }
      ]
    },
    {
      "label": "club room",
      "works": [
        {
          "slug": "494370bc-1962-46a6-b7f1-067a058d6f9b-2",
          "ar": 1.0,
          "key": "494370BC"
        },
        {
          "slug": "a4-28-3-3",
          "ar": 0.9992,
          "key": "A4 - 28 (3)"
        }
      ]
    },
    {
      "label": "prostor",
      "works": [
        {
          "slug": "swinwarrior1998-3",
          "ar": 1.2557,
          "key": "swinwarrior1998"
        },
        {
          "slug": "image-67",
          "ar": 0.8744,
          "key": "image 67"
        },
        {
          "slug": "image-68",
          "ar": 1.4814,
          "key": "image 68"
        }
      ]
    },
    {
      "label": "posters",
      "works": [
        {
          "slug": "type-w",
          "ar": 1.2263,
          "video": true,
          "key": "type-w"
        },
        {
          "slug": "just-a-regular-rock-2",
          "ar": 1.0,
          "key": "just a regular rock"
        },
        {
          "slug": "double-poster-mockup-2",
          "ar": 1.7572,
          "key": "Double_Poster_Mockup"
        },
        {
          "slug": "photo-2022-04-30-01-28-01-2",
          "ar": 1.0,
          "key": "photo_2022-04-30"
        },
        {
          "slug": "sea-view-rock-2",
          "ar": 0.9985,
          "key": "sea view rock"
        }
      ]
    },
    {
      "label": "jinx bomb",
      "works": [
        {
          "slug": "frame-21-2",
          "ar": 1.0,
          "key": "Frame 21"
        },
        {
          "slug": "untitled-2024-05-13-12-05-40-utc-1",
          "ar": 1.2635,
          "key": "untitled"
        },
        {
          "slug": "img-0041-1",
          "ar": 0.6447,
          "key": "IMG_0041"
        },
        {
          "slug": "image-70",
          "ar": 0.4634,
          "key": "image 70"
        },
        {
          "slug": "camphoto-351212254-3",
          "ar": 1.0,
          "key": "camphoto_351212254"
        },
        {
          "slug": "img-2659-2",
          "ar": 1.2815,
          "key": "IMG_2659"
        }
      ]
    }
  ]
};
