#!/usr/bin/env python3
"""Image pipeline for the portfolio.

Reads the source art from rt/*.png, flattens each onto the site's canvas colour
(so transparent rounded corners never flash white), writes three WebP widths per
work into assets/img/, and emits js/images.js — the manifest the page reads.

Run:  python3 build.py
Needs: Pillow  (pip install pillow)
"""
import glob
import json
import os
import shutil
from PIL import Image

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "rt")
OUT_IMG = os.path.join(ROOT, "assets", "img")
CANVAS = (35, 36, 39)            # #232427 — must match --canvas in style.css
WIDTHS = [480, 900, 1500]
QUALITY = 80

# how the 18 works split into scroll groups; rename freely, add groups freely.
GROUP_LABELS = ["group 1", "group 2", "group 3"]


def slugify(index):
    return f"w{index:02d}"


def main():
    os.makedirs(OUT_IMG, exist_ok=True)
    for f in glob.glob(os.path.join(OUT_IMG, "*.webp")):
        os.remove(f)

    files = sorted(glob.glob(os.path.join(SRC, "*.png")))
    if not files:
        raise SystemExit("no source images in rt/")

    works = []
    for i, path in enumerate(files, start=1):
        slug = slugify(i)
        im = Image.open(path).convert("RGBA")
        flat = Image.new("RGB", im.size, CANVAS)
        flat.paste(im, mask=im.split()[3])
        ow, oh = flat.size
        ar = round(ow / oh, 4)

        sizes = []
        for w in WIDTHS:
            if w > ow:
                w = ow
            h = round(w * oh / ow)
            resized = flat if (w, h) == (ow, oh) else flat.resize((w, h), Image.LANCZOS)
            out = os.path.join(OUT_IMG, f"{slug}-{w}.webp")
            resized.save(out, "WEBP", quality=QUALITY, method=6)
            sizes.append(w)
            if w == ow:
                break
        works.append({"slug": slug, "ar": ar, "sizes": sorted(set(sizes))})
        print(f"  {slug}  {ow}x{oh}  ar={ar}  -> {sorted(set(sizes))}")

    # logo: copy through as-is (small white monogram, transparent)
    os.makedirs(os.path.join(ROOT, "assets"), exist_ok=True)
    shutil.copyfile(os.path.join(ROOT, "Vector.png"), os.path.join(ROOT, "assets", "logo.png"))

    # split into groups (even chunks, last group takes the remainder)
    n = len(works)
    ngroups = min(len(GROUP_LABELS), n)
    per = -(-n // ngroups)
    groups = []
    for gi in range(ngroups):
        chunk = works[gi * per:(gi + 1) * per]
        if not chunk:
            break
        groups.append({"label": GROUP_LABELS[gi], "works": chunk})

    manifest = {
        "logo": "assets/logo.png",
        "imgBase": "assets/img",
        "widths": WIDTHS,
        "groups": groups,
    }
    js = "/* generated by build.py — do not edit by hand */\n"
    js += "window.SITE = " + json.dumps(manifest, ensure_ascii=False, indent=2) + ";\n"
    with open(os.path.join(ROOT, "js", "images.js"), "w") as fh:
        fh.write(js)
    print(f"\nwrote js/images.js — {len(groups)} groups, {n} works")


if __name__ == "__main__":
    main()
