#!/usr/bin/env python3
"""Image pipeline for the portfolio.

Reads the source art from rt/*.png, writes three WebP widths per work into
assets/img/ (keeping the alpha — the exports already carry rounded corners, so
we never paint a background behind them), and emits js/images.js, the manifest
the page reads.

Run:  python3 build.py
Needs: Pillow  (pip install pillow)
"""
import glob
import json
import os
import re
import shutil
from PIL import Image

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "rt")
OUT_IMG = os.path.join(ROOT, "assets", "img")
WIDTHS = [480, 900, 1500]
QUALITY = 82

# ----------------------------------------------------------------------------
# The board is columns (kanban on wide screens; a single scroll feed on phones).
# Each entry below is a column: a label and an ordered list of source files,
# matched by a case-insensitive substring of the filename. Reorder freely,
# move a file between columns, rename a label — all safe, nothing is keyed by
# position any more. Files listed in EXCLUDE are dropped; any file that matches
# nothing lands in a trailing "more" column so it is never lost silently.
COLUMNS = [
    ("petals",    ["IMG_2159", "abstrakt_cover (2)"]),
    ("club room", ["494370BC", "subrosa (4)", "A4 - 28 (3)"]),
    ("prostor",   ["Frame 1907", "swinwarrior1998", "image 53"]),
    ("posters",   ["Double_Poster_Mockup", "sea view rock"]),
    ("jinx bomb", ["Frame 21", "image 51", "IMG_6242"]),
    ("3d",        ["IMG_2659", "camphoto_351212254"]),
    ("type",      ["image 60"]),
]
EXCLUDE = ["9757D019", "MOCKUP-01", "image 50"]


def slugify(path):
    stem = os.path.splitext(os.path.basename(path))[0]
    return re.sub(r"[^a-z0-9]+", "-", stem.lower()).strip("-")


def encode(path):
    slug = slugify(path)
    im = Image.open(path).convert("RGBA")
    ow, oh = im.size
    for w in WIDTHS:
        tw = min(w, ow)
        th = round(tw * oh / ow)
        resized = im if (tw, th) == (ow, oh) else im.resize((tw, th), Image.LANCZOS)
        resized.save(os.path.join(OUT_IMG, f"{slug}-{w}.webp"), "WEBP", quality=QUALITY, method=6)
        if tw == ow:
            break
    return {"slug": slug, "ar": round(ow / oh, 4)}


def main():
    os.makedirs(OUT_IMG, exist_ok=True)
    for f in glob.glob(os.path.join(OUT_IMG, "*.webp")):
        os.remove(f)

    files = [f for f in sorted(glob.glob(os.path.join(SRC, "*.png")))
             if not any(x.lower() in os.path.basename(f).lower() for x in EXCLUDE)]
    if not files:
        raise SystemExit("no source images in rt/")

    def match(token):
        hits = [f for f in files if token.lower() in os.path.basename(f).lower()]
        if len(hits) != 1:
            raise SystemExit(f"COLUMNS token {token!r} matched {len(hits)} files: {[os.path.basename(h) for h in hits]}")
        return hits[0]

    used, columns = set(), []
    for label, tokens in COLUMNS:
        picked = []
        for t in tokens:
            path = match(t)
            used.add(path)
            picked.append(encode(path))
            print(f"  {label:10}  {os.path.basename(path)}")
        if picked:
            columns.append({"label": label, "works": picked})

    leftover = [f for f in files if f not in used]
    if leftover:
        columns.append({"label": "more", "works": [encode(f) for f in leftover]})
        for f in leftover:
            print(f"  {'more':10}  {os.path.basename(f)}")

    os.makedirs(os.path.join(ROOT, "assets"), exist_ok=True)
    shutil.copyfile(os.path.join(ROOT, "Vector.png"), os.path.join(ROOT, "assets", "logo.png"))

    manifest = {
        "logo": "assets/logo.png",
        "imgBase": "assets/img",
        "widths": WIDTHS,
        "columns": columns,
    }
    with open(os.path.join(ROOT, "js", "images.js"), "w") as fh:
        fh.write("/* generated by build.py — do not edit by hand */\n")
        fh.write("window.SITE = " + json.dumps(manifest, ensure_ascii=False, indent=2) + ";\n")
    total = sum(len(c["works"]) for c in columns)
    print(f"\nwrote js/images.js — {len(columns)} columns, {total} works")


if __name__ == "__main__":
    main()
