#!/usr/bin/env python3
"""Image pipeline for the portfolio.

Reads the source art from rt/*.png, writes three WebP widths per work into
assets/img/ (keeping the alpha — the exports already carry rounded corners, so
we never paint a background behind them), and emits js/images.js, the manifest
the page reads.

Run:  python3 build.py
Needs: Pillow  (pip install pillow)
"""
import glob
import json
import os
import shutil
from PIL import Image

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "rt")
OUT_IMG = os.path.join(ROOT, "assets", "img")
WIDTHS = [480, 900, 1500]
QUALITY = 82

# ----------------------------------------------------------------------------
# The board is columns, kanban-style. Each column is one series; on phones each
# column becomes its own stacking section. Slugs are w01..wNN in rt/ filename
# order (run once to see the mapping printed, then arrange below).
# Reorder columns, move slugs between them, rename labels — all safe.
# Any slug not listed is appended to a final "more" column so nothing is lost.
COLUMNS = [
    ("petals",    ["w06", "w10"]),
    ("club room", ["w01", "w02", "w17"]),
    ("prostor",   ["w04", "w18", "w14"]),
    ("posters",   ["w03", "w09", "w16"]),
    ("jinx bomb", ["w05", "w13", "w08"]),
    ("3d",        ["w07", "w11"]),
    ("type",      ["w12", "w15"]),
]


def slugify(index):
    return f"w{index:02d}"


def main():
    os.makedirs(OUT_IMG, exist_ok=True)
    for f in glob.glob(os.path.join(OUT_IMG, "*.webp")):
        os.remove(f)

    files = sorted(glob.glob(os.path.join(SRC, "*.png")))
    if not files:
        raise SystemExit("no source images in rt/")

    works = {}
    for i, path in enumerate(files, start=1):
        slug = slugify(i)
        im = Image.open(path).convert("RGBA")
        ow, oh = im.size
        ar = round(ow / oh, 4)

        for w in WIDTHS:
            tw = min(w, ow)
            th = round(tw * oh / ow)
            resized = im if (tw, th) == (ow, oh) else im.resize((tw, th), Image.LANCZOS)
            resized.save(os.path.join(OUT_IMG, f"{slug}-{w}.webp"),
                         "WEBP", quality=QUALITY, method=6)
            if tw == ow:
                break
        works[slug] = {"slug": slug, "ar": ar}
        print(f"  {slug}  {ow}x{oh}  ar={ar}  <-  {os.path.basename(path)}")

    # logo passes through untouched (small white monogram, transparent)
    os.makedirs(os.path.join(ROOT, "assets"), exist_ok=True)
    shutil.copyfile(os.path.join(ROOT, "Vector.png"), os.path.join(ROOT, "assets", "logo.png"))

    # assemble columns from COLUMNS; sweep any unplaced slug into a trailing column
    used = set()
    columns = []
    for label, slugs in COLUMNS:
        picked = [works[s] for s in slugs if s in works]
        used.update(s for s in slugs if s in works)
        if picked:
            columns.append({"label": label, "works": picked})
    leftover = [works[s] for s in sorted(works) if s not in used]
    if leftover:
        columns.append({"label": "more", "works": leftover})

    manifest = {
        "logo": "assets/logo.png",
        "imgBase": "assets/img",
        "widths": WIDTHS,
        "columns": columns,
    }
    js = "/* generated by build.py — do not edit by hand */\n"
    js += "window.SITE = " + json.dumps(manifest, ensure_ascii=False, indent=2) + ";\n"
    with open(os.path.join(ROOT, "js", "images.js"), "w") as fh:
        fh.write(js)
    total = sum(len(c["works"]) for c in columns)
    print(f"\nwrote js/images.js — {len(columns)} columns, {total} works")


if __name__ == "__main__":
    main()
